import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { PGlite } from "@electric-sql/pglite";
import type { Pool } from "pg";
import { createServer } from "node:http";
import { PostgresManifestUploads, ManifestUploadError, hashBytes, MAX_MANIFEST_UPLOAD_BYTES } from "../src/manifestUploads";
import { nativeFileUrl, isPublicIpv4 } from "../src/nativeManifestFile";
import { createManifestUploadHandler } from "../src/webManifestUploads";
import { neutralManifest } from "./protocol-fixtures";

const db = new PGlite();
try {
  await db.exec(await readFile(new URL("../migrations/001-domain.sql", import.meta.url), "utf8"));
  const migration = await readFile(new URL("../migrations/003-manifest-uploads.sql", import.meta.url), "utf8");
  await db.exec(migration); await db.exec(migration);
  let tail: Promise<void> = Promise.resolve();
  const query = (sql: string, values?: unknown[]) => db.query(sql, values);
  const pool = { query, async connect() { const previous = tail; let release!: () => void; tail = new Promise<void>(resolve => { release = resolve; }); await previous; return { query, release }; } };
  const uploads = new PostgresManifestUploads(pool as unknown as Pick<Pool, "query" | "connect">);
  const fails = (status: number) => (error: unknown) => error instanceof ManifestUploadError && error.status === status;
  const bytes = Buffer.from(JSON.stringify(neutralManifest()));
  const first = await uploads.create("alice", bytes.length, hashBytes(bytes));
  await assert.rejects(uploads.read("alice", first.uploadId), fails(409));
  await assert.rejects(uploads.finalize(first.uploadId, "x".repeat(43), bytes), fails(404));
  await assert.rejects(uploads.finalize(first.uploadId, first.ticket, Buffer.from("{}")), fails(400));
  const finalized = await uploads.finalize(first.uploadId, first.ticket, bytes);
  assert.equal(finalized.sha256, hashBytes(bytes));
  assert.equal(finalized.validation.valid, true);
  assert.deepEqual(await uploads.finalize(first.uploadId, first.ticket, bytes), finalized);
  await assert.rejects(uploads.read("bob", first.uploadId), fails(404));
  await assert.rejects(uploads.import("bob", first.uploadId), fails(404));
  const read = await uploads.read("alice", first.uploadId); assert.equal(read.json, bytes.toString());
  const imported = await uploads.import("alice", first.uploadId);
  const repeated = await Promise.all(Array.from({length: 5}, () => uploads.import("alice", first.uploadId)));
  for (const result of repeated) assert.deepEqual(result, imported);
  assert.equal((await db.query<{count:number}>("SELECT count(*)::int AS count FROM arcana_user_decks")).rows[0].count, 1);
  assert.equal((await db.query<{raw_json:string|null}>("SELECT raw_json FROM arcana_manifest_uploads WHERE id=$1", [first.uploadId])).rows[0].raw_json, null);
  await assert.rejects(uploads.import("alice", first.uploadId, {deckId:String(imported.id),expectedRevision:1}), fails(409));
  const nextBytes = Buffer.from(JSON.stringify({...neutralManifest(), tagline:"Changed"}));
  const next = await uploads.create("alice", nextBytes.length);
  await uploads.finalize(next.uploadId, next.ticket, nextBytes);
  const options = {deckId:String(imported.id),expectedRevision:1};
  const changed = await uploads.import("alice", next.uploadId, options);
  assert.equal(changed.revision, 2);
  assert.deepEqual(await uploads.import("alice", next.uploadId, options), changed);
  const stale = await uploads.create("alice", bytes.length); await uploads.finalize(stale.uploadId, stale.ticket, bytes);
  await assert.rejects(uploads.import("alice", stale.uploadId, options), fails(409));
  const invalid = await uploads.create("alice", 2); const badReport = await uploads.finalize(invalid.uploadId, invalid.ticket, Buffer.from("{}"));
  assert.equal(badReport.validation.valid, false); assert.ok(badReport.validation.errors.length > 1);
  await assert.rejects(uploads.import("alice", invalid.uploadId), fails(400));
  const raw = await uploads.create("raw", 2); await uploads.finalize(raw.uploadId, raw.ticket, Buffer.from("{}"));
  await assert.rejects(uploads.finalize(raw.uploadId, raw.ticket, Buffer.from("[]")), fails(409));
  await db.query("UPDATE arcana_manifest_uploads SET expires_at=now()-interval '1 second' WHERE id=$1", [raw.uploadId]);
  await assert.rejects(uploads.read("raw", raw.uploadId), fails(404));
  await assert.rejects(uploads.import("raw", raw.uploadId), fails(404));
  await assert.rejects(uploads.finalize(raw.uploadId, raw.ticket, Buffer.from("{}")), fails(404));
  await uploads.create("raw", 2);
  assert.equal((await db.query("SELECT id FROM arcana_manifest_uploads WHERE id=$1", [raw.uploadId])).rows.length, 0);
  const orphan = await uploads.create("dormant", 2);
  await db.query("UPDATE arcana_manifest_uploads SET expires_at=now()-interval '1 second' WHERE id=$1", [orphan.uploadId]);
  assert.equal(await uploads.pruneExpired(), 1);
  assert.equal((await db.query("SELECT id FROM arcana_manifest_uploads WHERE id=$1", [orphan.uploadId])).rows.length, 0);
  await assert.rejects(uploads.import("alice", stale.uploadId, { deckId: "", expectedRevision: 1 }), fails(400));
  const concurrent = await Promise.allSettled(Array.from({length: 12}, () => uploads.create("quota", 2)));
  assert.equal(concurrent.filter(result => result.status === "fulfilled").length, 8);
  await assert.rejects(uploads.create("bad", MAX_MANIFEST_UPLOAD_BYTES+1), fails(400));
  for (const address of ["127.0.0.1","10.0.0.1","169.254.169.254","172.16.0.1","192.168.1.1","100.64.1.1","0.0.0.0","224.1.1.1","198.18.1.1","::1"]) assert.equal(isPublicIpv4(address), false, address);
  assert.equal(isPublicIpv4("8.8.8.8"), true);
  for (const url of ["http://files.oaiusercontent.com/a","https://files.oaiusercontent.com.evil.test/a","https://127.0.0.1/a","https://foo.blob.core.windows.net/a","https://files.oaiusercontent.com:8443/a","https://user@files.oaiusercontent.com/a"]) assert.throws(() => nativeFileUrl(url));
  assert.equal(nativeFileUrl("https://files.oaiusercontent.com/test?token=secret").hostname, "files.oaiusercontent.com");
  const handler = createManifestUploadHandler(uploads);
  const server = createServer((req,res) => void handler(req,res));
  await new Promise<void>(resolve => server.listen(0,"127.0.0.1",resolve));
  try {
    const address = server.address(); assert.ok(address && typeof address !== "string");
    const ticket = await uploads.create("http", bytes.length,hashBytes(bytes));
    const url = `http://127.0.0.1:${address.port}/api/manifest-uploads/${ticket.uploadId}`;
    const headers = {"content-type":"application/json",authorization:`Bearer ${ticket.ticket}`};
    assert.equal((await fetch(url,{method:"PUT",body:bytes,headers})).status,200);
    assert.equal((await fetch(url,{method:"PUT",body:bytes,headers})).status,200);
    assert.equal((await fetch(url,{method:"GET",headers})).status,405);
    assert.equal((await fetch(url,{method:"PUT",body:bytes,headers:{"content-type":"application/json"}})).status,401);
    assert.equal((await fetch(url,{method:"PUT",body:bytes,headers:{...headers,"content-type":"text/html"}})).status,415);
    assert.equal((await fetch(url,{method:"PUT",body:bytes,headers:{...headers,"content-encoding":"gzip"}})).status,415);
    assert.equal((await fetch(url,{method:"PUT",body:Buffer.alloc(MAX_MANIFEST_UPLOAD_BYTES+1),headers})).status,413);
  } finally { await new Promise<void>((resolve,reject) => server.close(error=>error?reject(error):resolve())); }
  console.log("Manifest staging: immutable bytes, digests, expiry, quotas, isolation, idempotent transactional import, revision CAS, HTTP and SSRF policy passed (PostgreSQL/PGlite).");
} finally { await db.close(); }
