import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { PGlite } from "@electric-sql/pglite";
import type { Pool } from "pg";
import { PostgresManifestUploads, ManifestUploadError, ManifestDraftVersionConflict } from "../src/manifestUploads";
import { PostgresManifestDrafts } from "../src/manifestDrafts";
import { neutralManifest } from "./protocol-fixtures";
import { PostgresManifestUploads as PreDraftManifestUploads } from "./fixtures/pre-draft-manifest-uploads";

const db = new PGlite();
try {
  for (const file of ["001-domain.sql", "003-manifest-uploads.sql"])
    await db.exec(await readFile(new URL(`../migrations/${file}`, import.meta.url), "utf8"));
  await db.exec("INSERT INTO arcana_manifest_uploads(id,owner_id,ticket_hash,expected_bytes,raw_json,expires_at) VALUES('legacy-preexisting','legacy-preexisting','opaque',2,'{}',now()+interval '15 minutes')");
  const draftMigration = await readFile(new URL("../migrations/005-manifest-drafts.sql", import.meta.url), "utf8");
  await db.exec(draftMigration); await db.exec(draftMigration);
  const preserved = (await db.query<{raw_json:string;draft_json:null}>("SELECT raw_json,draft_json FROM arcana_manifest_uploads WHERE id='legacy-preexisting'")).rows[0];
  assert.deepEqual(preserved,{raw_json:"{}",draft_json:null});
  let tail: Promise<void> = Promise.resolve();
  let failReceipt = false;
  const query = async (sql: string, values?: unknown[]) => {
    if (failReceipt && sql.startsWith("UPDATE arcana_manifest_uploads SET raw_json=NULL")) throw new Error("Synthetic receipt write failure");
    return db.query(sql, values);
  };
  // PGlite is a single connection: tests prove SQL atomicity/retries, not independent PostgreSQL sessions.
  const pool = { query, async connect() { const prior = tail; let release!: () => void; tail = new Promise<void>(resolve => {release = resolve;}); await prior; return { query, release }; } } as unknown as Pick<Pool,"query"|"connect">;
  const uploads = new PostgresManifestUploads(pool);
  const oldDeployment = new PreDraftManifestUploads(pool);
  const drafts = new PostgresManifestDrafts(pool, uploads);
  const replica = new PostgresManifestDrafts(pool, new PostgresManifestUploads(pool));
  const fails = (status: number) => (error: unknown) => error instanceof ManifestUploadError && error.status === status;
  const count = async () => (await db.query<{count:number}>("SELECT count(*)::int AS count FROM arcana_user_decks")).rows[0].count;
  const row = async (id: unknown) => (await db.query<Record<string,any>>("SELECT * FROM arcana_manifest_uploads WHERE id=$1", [id])).rows[0];
  const fill = async (owner: string, startKey: string, slug = startKey) => {
    let draft = await drafts.start(owner, startKey);
    const manifest = neutralManifest(slug);
    const {cards,suits,ranks,transversal,...metadata} = manifest.data;
    const {stations,...txMetadata} = transversal;
    const input = { draftId:draft.draftId, expectedVersion:draft.version, mutationId:"structure", metadata:{schemaVersion:manifest.schemaVersion,tagline:manifest.tagline,data:metadata}, transversal:txMetadata };
    draft = await drafts.update(owner,input);
    draft = await drafts.update(owner,{draftId:draft.draftId,expectedVersion:draft.version,mutationId:"axes",suits:{upsert:Object.entries(suits).map(([key,value])=>({key,value}))},ranks:{upsert:Object.entries(ranks).map(([key,value])=>({key,value}))},stations:{upsert:Object.entries(stations).map(([key,value])=>({key,value}))}});
    return drafts.update(owner,{draftId:draft.draftId,expectedVersion:draft.version,mutationId:"cards",cards:{upsert:Object.values(cards)}});
  };
  const started = await drafts.start("alice","resume-key");
  assert.equal(started.version,1);
  assert.equal(started.sha256Basis,"assembled-json-sorted-keys-compact-utf8-v1");
  assert.equal(started.state,"editing");
  assert.deepEqual(await replica.start("alice","resume-key"),started);
  assert.equal((await row(started.draftId)).draft_key,"resume-key");
  assert.equal((await row(started.draftId)).raw_json,null,"old deployments cannot read editable drafts as finalized upload bytes");
  await assert.rejects(db.query("UPDATE arcana_manifest_uploads SET raw_json='{}' WHERE id=$1",[started.draftId]),/arcana_manifest_draft_bounds/);
  assert.equal(await count(),0);
  const emptyReport = await drafts.validate("alice",String(started.draftId),1);
  assert.equal((emptyReport.validation as {valid:boolean}).valid,false);
  await assert.rejects(drafts.commit("alice",String(started.draftId),1),fails(400));
  for (const op of [() => replica.read("bob",{draftId:started.draftId}), () => drafts.validate("bob",String(started.draftId),1), () => drafts.commit("bob",String(started.draftId),1)]) await assert.rejects(op,fails(404));
  await assert.rejects(uploads.import("alice",String(started.draftId)),fails(409));
  await assert.rejects(uploads.read("alice",String(started.draftId)),fails(409));
  const update = {draftId:started.draftId,expectedVersion:1,mutationId:"first",metadata:{tagline:"A first line."}};
  const changed = await drafts.update("alice",update);
  assert.equal(changed.version,2);
  assert.equal(changed.sha256Basis,started.sha256Basis);
  assert.equal(changed.expiresAt,started.expiresAt,"writes cannot extend expiry indefinitely");
  const replay = await replica.update("alice",update);
  assert.equal(replay.replayed,true); assert.equal(replay.version,2);
  await assert.rejects(drafts.update("alice",{...update,metadata:{tagline:"Different"}}),fails(409));
  await assert.rejects(drafts.update("bob",update),fails(404));
  await assert.rejects(drafts.update("alice",{...update,mutationId:"stale"}),error => error instanceof ManifestDraftVersionConflict && error.currentVersion===2);
  const competing = await Promise.allSettled(["one","two"].map(mutationId=>drafts.update("alice",{...update,mutationId,expectedVersion:2})));
  assert.equal(competing.filter(r=>r.status==="fulfilled").length,1);
  assert.equal((await replica.read("alice",{draftId:started.draftId})).version,3);
  const replayLater = await replica.update("alice",update); assert.equal(replayLater.version,2); assert.equal(replayLater.currentVersion,3);
  const ready = await fill("alice","ready-deck");
  // Run the actual pre-draft implementation against a valid new draft, not only our new guards.
  await assert.rejects(oldDeployment.read("alice",String(ready.draftId)),/not finalized/);
  await assert.rejects(oldDeployment.import("alice",String(ready.draftId)),/Upload bytes before importing/);
  const validated = await replica.validate("alice",String(ready.draftId),Number(ready.version));
  assert.equal((validated.validation as {valid:boolean}).valid,true);
  assert.equal(validated.sha256Basis,started.sha256Basis);
  assert.equal(await count(),0,"validating does not insert a catalog deck");
  const partial = await replica.read("alice",{draftId:ready.draftId,section:"cards",limit:2});
  assert.equal(((partial.part as {entries:unknown[]}).entries).length,2);
  await assert.rejects(drafts.commit("alice",String(ready.draftId),Number(ready.version)-1),fails(409));
  failReceipt=true;
  await assert.rejects(drafts.commit("alice",String(ready.draftId),Number(ready.version)),/Synthetic/);
  failReceipt=false;
  assert.equal(await count(),0,"catalog insert rolls back when receipt write fails");
  assert.notEqual((await row(ready.draftId)).draft_json,null);
  assert.equal((await row(ready.draftId)).raw_json,null,"old deployment imports see no finalized source bytes");
  const receipts = await Promise.all(Array.from({length:4},()=>drafts.commit("alice",String(ready.draftId),Number(ready.version))));
  for (const receipt of receipts) assert.deepEqual(receipt,receipts[0]);
  assert.equal(receipts[0].sha256Basis,started.sha256Basis);
  await db.query("UPDATE arcana_manifest_uploads SET import_result=import_result-'sha256Basis' WHERE id=$1",[ready.draftId]);
  assert.equal((await drafts.commit("alice",String(ready.draftId),Number(ready.version))).sha256Basis,started.sha256Basis,"old receipts gain response metadata without rewriting stored data");
  assert.equal(await count(),1);
  assert.equal((await row(ready.draftId)).raw_json,null);
  assert.equal((await row(ready.draftId)).draft_json,null);
  assert.equal((await replica.read("alice",{draftId:ready.draftId})).state,"committed");
  assert.equal((await drafts.start("alice","ready-deck")).state,"committed");
  await assert.rejects(drafts.commit("alice",String(ready.draftId),Number(ready.version),{deckId:String(receipts[0].id),expectedRevision:1}),fails(409));
  await assert.rejects(drafts.update("alice",{draftId:ready.draftId,expectedVersion:ready.version,mutationId:"after-commit",metadata:{tagline:"No"}}),fails(409));
  const replacement = await fill("alice","replacement","ready-deck");
  const opts={deckId:String(receipts[0].id),expectedRevision:1};
  const updated = await drafts.commit("alice",String(replacement.draftId),Number(replacement.version),opts);
  assert.equal(updated.revision,2);
  assert.deepEqual(await drafts.commit("alice",String(replacement.draftId),Number(replacement.version),opts),updated);
  const stale = await fill("alice","stale-replacement","ready-deck");
  await assert.rejects(drafts.commit("alice",String(stale.draftId),Number(stale.version),opts),fails(409));
  assert.equal((await row(stale.draftId)).import_result,null);
  const raw=await uploads.create("legacy",2); await uploads.finalize(raw.uploadId,raw.ticket,Buffer.from("{}"));
  await assert.rejects(drafts.commit("legacy",raw.uploadId,1),fails(404));
  const quotaDraft = await drafts.start("quota","first");
  for(let i=0;i<7;i++) await uploads.create("quota",2);
  await assert.rejects(drafts.start("quota","ninth"),fails(429));
  await assert.rejects(uploads.create("quota",2),fails(429));
  assert.equal((await drafts.start("quota","first")).draftId,quotaDraft.draftId,"idempotent start succeeds at quota");
  const limit=await drafts.start("limit","limit");
  const history=Object.fromEntries(Array.from({length:512},(_,i)=>[`id-${i}`,{sha256:"a".repeat(64),version:i+2}]));
  await db.query("UPDATE arcana_manifest_uploads SET draft_version=513,draft_history=$2::jsonb WHERE id=$1",[limit.draftId,JSON.stringify(history)]);
  await assert.rejects(drafts.update("limit",{draftId:limit.draftId,expectedVersion:513,mutationId:"exhausted",metadata:{tagline:"No"}}),fails(429));
  await db.query("UPDATE arcana_manifest_uploads SET expires_at=now()-interval '1 second' WHERE id=$1",[started.draftId]);
  await assert.rejects(replica.read("alice",{draftId:started.draftId}),fails(404));
  await assert.rejects(drafts.commit("alice",String(started.draftId),3),fails(404));
  assert.equal(await uploads.pruneExpired(),1);
  assert.equal(await row(started.draftId),undefined);
  console.log("Incremental draft SQL: additive migration, isolation, shared quotas, version conflicts, retry keys, resume, validation, atomic rollback/receipt, replacement CAS and expiry passed (single-connection PostgreSQL/PGlite).");
} finally { await db.close(); }
