import assert from 'node:assert/strict';
import { PGlite } from '@electric-sql/pglite';
import { catalog, run, schema, type Connection } from '../scripts/domain-migrations';
import { diagnoseSchema } from '../scripts/migration-schema-diagnostics';
const entries=await catalog();
const db=new PGlite();
const statements:string[]=[];
const adapter:Connection={query:async(sql,values)=>{statements.push(sql);if(values)return db.query(sql,values);return {rows:(await db.exec(sql)).at(-1)?.rows??[]};}};
try {
  for(const entry of entries.slice(0,5)) await adapter.query(entry.sql);
  await adapter.query("ALTER TABLE arcana_host_state ALTER COLUMN state DROP NOT NULL; ALTER TABLE arcana_host_state ALTER COLUMN state SET DEFAULT '{\"do_not_log\":\"private-literal\"}'::jsonb");
  const before=await schema(adapter);
  statements.length=0;
  const result=await run(adapter,entries,'plan');
  assert.equal(result.verifiedBaselineCandidate,null);
  assert.equal(result.baselineRequired,true);
  assert.ok(result.schemaDiagnostics);
  assert.equal(result.diagnosticContext?.transaction_read_only,'on');
  assert.match(result.diagnosticContext?.server_version_num ?? '',/^\d+$/);
  assert.ok(statements[0]==='BEGIN READ ONLY');
  assert.ok(statements.every(sql=>/^(SELECT|SET LOCAL|BEGIN READ ONLY|COMMIT)/.test(sql)), 'diagnostic must issue only existing read-only metadata plan statements');
  const output=JSON.stringify(result);
  assert.ok(!output.includes('private-literal')&&!output.includes('do_not_log'));
  assert.ok(output.includes('public.arcana_host_state.columns'));
  assert.ok(output.includes('notNull'));
  assert.deepEqual(await schema(adapter),before);
  assert.equal((await adapter.query("SELECT to_regclass('public.arcana_migration_history') AS ledger")).rows[0].ledger,null);
  const v5=result.schemaDiagnostics!.comparisons.find(x=>x.version===5)!;
  assert.equal(v5.differenceCount,2);
  assert.equal(v5.exactSnapshotMatch,false);
  assert.ok(v5.differences?.some(x=>x.expected===true&&x.actual===false));
  const reordered=entries[4].schema.map((x:any)=>Object.fromEntries(Object.entries(x).reverse()));
  const ordering=diagnoseSchema(reordered,[entries[4]]).comparisons[0];
  assert.equal(ordering.differenceCount,0);
  assert.equal(ordering.exactSnapshotMatch,false,'diagnostics must not weaken strict baseline matching');
  const exact=diagnoseSchema(entries[4].schema,[entries[4]]).comparisons[0];
  assert.equal(exact.exactSnapshotMatch,true);
  const unusual=diagnoseSchema([{name:'secret://do-not-print',columns:[['odd name','literal-secret']]}],entries);
  assert.ok(!JSON.stringify(unusual).includes('secret://do-not-print'));
  console.log('Schema diagnostic tests passed: read-only metadata statements, unchanged schema/no ledger, literal redaction, field differences, serialization-order detection, exact matching.');
} finally {await db.close();}
